#!/bin/bash
ua="$1"
plist="$2"
mpl() {
    mplayer -quiet -http-header-fields "User-Agent: ${ua}" -playlist "$@"
}
cat_plist() {
    red=$(tput bold;tput setaf 1)
    normal=$(tput sgr0)
    cat "$plist" | sed -e "s/\(flv\/fileid\/[A-F0-9]\{9\}\)\([A-F0-9]\)/\1$red\2$normal/"
}
cat_plist
while read -p "Start from part: " i
do
    if [[ "$i" =~ ^[0-9]+$ ]]; then
        sed "1,${i}d" "$plist" >"${plist}.sed"
        mpl "${plist}.sed"
    else
        mpl "$plist"
    fi
echo
cat_plist
done
